apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: redis
  namespace: {{ include "redis-sentinel-openshift-proxy.namespace" . }}
spec:
  serviceName: redis-headless
  replicas: {{ .Values.redis.replicas }}
  selector:
    matchLabels:
      app: redis
  template:
    metadata:
      labels:
        app: redis
    spec:
      serviceAccountName: default
      securityContext:
{{ toYaml .Values.podSecurityContext | indent 8 }}
      containers:
        - name: redis
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          command: ["/opt/redis/scripts/entrypoint.sh", "redis"]
          env:
            - name: POD_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: MASTER_NAME
              value: {{ .Values.redis.masterName | quote }}
            - name: MASTER_HOST
              value: {{ printf "redis-0.redis-headless.%s.svc.cluster.local" (include "redis-sentinel-openshift-proxy.namespace" .) | quote }}
            - name: MASTER_PORT
              value: {{ .Values.redis.port | quote }}
          ports:
            - containerPort: {{ .Values.redis.port }}
              name: redis
          volumeMounts:
            - name: redis-data
              mountPath: /data
            - name: redis-config
              mountPath: /opt/redis/conf/redis.conf
              subPath: redis.conf
            - name: sentinel-config
              mountPath: /opt/redis/conf/sentinel.conf
              subPath: sentinel.conf
          readinessProbe:
            tcpSocket:
              port: {{ .Values.redis.port }}
            initialDelaySeconds: 10
            periodSeconds: 10
          livenessProbe:
            tcpSocket:
              port: {{ .Values.redis.port }}
            initialDelaySeconds: 20
            periodSeconds: 10
          securityContext:
{{ toYaml .Values.securityContext | indent 12 }}
          resources:
{{ toYaml .Values.resources | indent 12 }}
      volumes:
        - name: redis-config
          configMap:
            name: redis-config
            items:
              - key: redis.conf
                path: redis.conf
        - name: sentinel-config
          configMap:
            name: redis-config
            items:
              - key: sentinel.conf
                path: sentinel.conf
  volumeClaimTemplates:
    - metadata:
        name: redis-data
      spec:
        accessModes: ["ReadWriteOnce"]
{{- if .Values.redis.storage.storageClassName }}
        storageClassName: {{ .Values.redis.storage.storageClassName | quote }}
{{- end }}
        resources:
          requests:
            storage: {{ .Values.redis.storage.size }}
