apiVersion: v1
kind: Service
metadata:
  name: redis
  namespace: {{ include "redis-sentinel-openshift-proxy.namespace" . }}
spec:
  selector:
    app: redis
  ports:
    - name: redis
      port: {{ .Values.redis.port }}
      targetPort: {{ .Values.redis.port }}
---
apiVersion: v1
kind: Service
metadata:
  name: redis-headless
  namespace: {{ include "redis-sentinel-openshift-proxy.namespace" . }}
spec:
  clusterIP: None
  publishNotReadyAddresses: true
  selector:
    app: redis
  ports:
    - name: redis
      port: {{ .Values.redis.port }}
      targetPort: {{ .Values.redis.port }}
---
apiVersion: v1
kind: Service
metadata:
  name: sentinel
  namespace: {{ include "redis-sentinel-openshift-proxy.namespace" . }}
spec:
  selector:
    app: sentinel
  ports:
    - name: sentinel
      port: {{ .Values.sentinel.port }}
      targetPort: {{ .Values.sentinel.port }}
---
apiVersion: v1
kind: Service
metadata:
  name: sentinel-headless
  namespace: {{ include "redis-sentinel-openshift-proxy.namespace" . }}
spec:
  clusterIP: None
  publishNotReadyAddresses: true
  selector:
    app: sentinel
  ports:
    - name: sentinel
      port: {{ .Values.sentinel.port }}
      targetPort: {{ .Values.sentinel.port }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.service.redisProxyName }}
  namespace: {{ include "redis-sentinel-openshift-proxy.namespace" . }}
spec:
  selector:
    app: redis-haproxy
  ports:
    - name: redis
      port: {{ .Values.haproxy.redisServicePort }}
      targetPort: {{ .Values.haproxy.redisServicePort }}
---
apiVersion: v1
kind: Service
metadata:
  name: redis-haproxy-stats
  namespace: {{ include "redis-sentinel-openshift-proxy.namespace" . }}
spec:
  selector:
    app: redis-haproxy
  ports:
    - name: stats
      port: {{ .Values.haproxy.statsPort }}
      targetPort: {{ .Values.haproxy.statsPort }}
