apiVersion: v1
kind: ConfigMap
metadata:
  name: redis-config
  namespace: redis-sentinel
data:
  redis.conf: |
    bind 0.0.0.0
    protected-mode no
    port 6379
    dir /data
    dbfilename dump.rdb
    appendonly yes
    appendfilename "appendonly.aof"
    appendfsync everysec
    save 900 1
    save 300 10
    save 60 10000
    logfile ""
    loglevel notice
    replica-read-only yes
  sentinel.conf: |
    port 26379
    bind 0.0.0.0
    protected-mode no
    logfile ""
    dir /tmp
    sentinel resolve-hostnames yes
    sentinel announce-hostnames yes
    sentinel monitor mymaster redis-0.redis-headless.redis-sentinel.svc.cluster.local 6379 2
    sentinel down-after-milliseconds mymaster 5000
    sentinel failover-timeout mymaster 60000
    sentinel parallel-syncs mymaster 1
  haproxy.cfg: |
    global
      log stdout format raw local0
      maxconn 20000
      stats socket /tmp/haproxy.sock mode 660 level admin expose-fd listeners
    defaults
      log global
      mode tcp
      option tcplog
      timeout connect 5s
      timeout client 60s
      timeout server 60s
      retries 3
    frontend redis_frontend
      bind *:6379
      default_backend redis_primary_backend
    backend redis_primary_backend
      mode tcp
      option tcp-check
      tcp-check connect
      tcp-check send PING\r\n
      tcp-check expect string +PONG
      tcp-check send info\ replication\r\n
      tcp-check expect string role:master
      tcp-check send QUIT\r\n
      tcp-check expect string +OK
      default-server inter 2s fall 3 rise 2 on-marked-down shutdown-sessions
      server redis-0 redis-0.redis-headless.redis-sentinel.svc.cluster.local:6379 check
      server redis-1 redis-1.redis-headless.redis-sentinel.svc.cluster.local:6379 check
      server redis-2 redis-2.redis-headless.redis-sentinel.svc.cluster.local:6379 check
    listen stats
      bind *:16379
      mode http
      stats enable
      stats uri /
      stats refresh 10s
