apiVersion: v1
kind: Service
metadata:
  name: redis
  namespace: redis-sentinel
spec:
  selector:
    app: redis
  ports:
    - name: redis
      port: 6379
      targetPort: 6379
---
apiVersion: v1
kind: Service
metadata:
  name: redis-headless
  namespace: redis-sentinel
spec:
  clusterIP: None
  publishNotReadyAddresses: true
  selector:
    app: redis
  ports:
    - name: redis
      port: 6379
      targetPort: 6379
---
apiVersion: v1
kind: Service
metadata:
  name: sentinel
  namespace: redis-sentinel
spec:
  selector:
    app: sentinel
  ports:
    - name: sentinel
      port: 26379
      targetPort: 26379
---
apiVersion: v1
kind: Service
metadata:
  name: sentinel-headless
  namespace: redis-sentinel
spec:
  clusterIP: None
  publishNotReadyAddresses: true
  selector:
    app: sentinel
  ports:
    - name: sentinel
      port: 26379
      targetPort: 26379
---
apiVersion: v1
kind: Service
metadata:
  name: redis-proxy
  namespace: redis-sentinel
spec:
  selector:
    app: redis-haproxy
  ports:
    - name: redis
      port: 6379
      targetPort: 6379
---
apiVersion: v1
kind: Service
metadata:
  name: redis-haproxy-stats
  namespace: redis-sentinel
spec:
  selector:
    app: redis-haproxy
  ports:
    - name: stats
      port: 16379
      targetPort: 16379
