bind 0.0.0.0
protected-mode no
port 6379

dir /data
dbfilename dump.rdb

appendonly yes
appendfilename "appendonly.aof"
appendfsync everysec

save 900 1
save 300 10
save 60 10000

loglevel notice
logfile ""

tcp-keepalive 300
timeout 0

replica-read-only yes
repl-diskless-sync yes
repl-diskless-sync-delay 5

lazyfree-lazy-eviction yes
lazyfree-lazy-expire yes

# Optional tuning
# maxmemory 1gb
# maxmemory-policy allkeys-lru
